vite-project-kabinet
JavaBorka/projekt-kabinet pull request #2
Opened 2024-11-10 05:47 UTC by JavaBorka

2024-11-11 17:56 UTC, fandasson commented
Nechceš mít složku `vite-project-kabinet`. Všechno co v té složce by mělo být v rootu repozitáře a ta složka tam nebýt. Nedává to smysl. Možná časem budeš v rootu složky `client` a `server`, ale možná ne, tak bych to teď nekomplikoval. Ale i kdybys tam tu složku chtěla mít, tak bych ji spíš pojmenoval třeba "client". `project-kabinet` je už v názvu repozitáře a že se používá `vite` je moc velký detail abys ho musela komunikovat skrze název složek

2024-11-11 17:56 UTC, fandasson commented
Vyber si nějaká pravidla pro názvy souborů a těch se drž. Zatím máš všechno konzistentní až na názvy obrázků, kde někde používáš _snake_case_ a jinde _kebab-case_.

2024-11-14 19:31 UTC, fandasson commented on vite-project-kabinet/src/Content/Card.jsx
> +            <p class="card__content">
Should `className`

2024-11-14 19:31 UTC, fandasson commented on vite-project-kabinet/src/Content/Card.jsx
> +    const cardClassName = () => {
Tohle by měla být komponenta a ne funkce

2024-11-14 19:32 UTC, fandasson commented on vite-project-kabinet/src/Content/Card.jsx
> +    const displayImage = () => {
Tohle by měla být komponenta a ne funkce

```suggestion
  const Image = (props) => {
  ....
  
```

2024-11-18 21:04 UTC, fandasson requested changes
Ještě posílám pro-formu pár drobností.

Mimochodem, pracovala jsi někdy s nějakým CSS preprocesorem (SASS, LESS)?

2024-11-18 21:04 UTC, fandasson commented on vite-project-kabinet/src/Content/Card.jsx
> +      <>
nitpic: Tady ten fragment je zbytečný. Máš tam jen jeden child element

2024-11-18 21:04 UTC, fandasson commented on vite-project-kabinet/src/Footer/Footer.jsx
> +                    <p className="fond__copyright">Copyright © 2024 KABINET | All rights reserved</p>
Drobnost, ale zkus si jako JS cvičení nahradit "2024" dynamickým výpisem aktuálního roku. Aby jsi to v lednu (každý rok) nemusela upravovat.

2024-11-19 18:15 UTC, JavaBorka commented
> Ještě posílám pro-formu pár drobností.
> 
> Mimochodem, pracovala jsi někdy s nějakým CSS preprocesorem (SASS, LESS)?

Áno, viem pracovať so SASS, ale prirodzenejšie mi bolo to tam takto nahádzať jak to je :) Možem to preklopiť do SASSu. Tá štruktúra ostane tak, jak je teraz? Len sa prípony zmenia na scss?

2024-11-19 22:16 UTC, fandasson commented
> Áno, viem pracovať so SASS, ale prirodzenejšie mi bolo to tam takto nahádzať jak to je :) Možem to preklopiť do SASSu. Tá štruktúra ostane tak, jak je teraz? Len sa prípony súborov zmenia na scss?

Jo, změna přípony by měla fungovat. Ale nemusíš to teď nutně měnit, šlo mi spíš o to, že se Ti tam začíná duplikovat kód a preprocessor by to přehledněji vyřešil. Ale to je něco, s čím má smysl si hrát později.

2024-11-20 11:36 UTC, JavaBorka commented
Zmeny som zapracovala, ale pushla som to omylom do branche feature/pagination.

2024-11-20 15:59 UTC, fandasson approved these changes

2024-11-22 18:57 UTC, merged